steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/utpanna-backend:$SHORT_SHA', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/utpanna-backend:$SHORT_SHA']
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        if [ "$BRANCH_NAME" == "develop" ]; then
          gcloud run deploy _SERVICE_NAME --image gcr.io/$PROJECT_ID/utpanna-backend:$SHORT_SHA --region $_DEPLOY_REGION --platform _PLATFORM;
        elif [ "$BRANCH_NAME" == "main" ]; then
          gcloud run deploy _SERVICE_NAME --image gcr.io/$PROJECT_ID/utpanna-backend:$SHORT_SHA --region $_DEPLOY_REGION --platform _PLATFORM;
        elif [[ "$TAG_NAME" == v* ]]; then
          gcloud run deploy _SERVICE_NAME --image gcr.io/$PROJECT_ID/utpanna-backend:$SHORT_SHA --region $_DEPLOY_REGION --platform _PLATFORM;
        fi
images:
  - 'gcr.io/$PROJECT_ID/utpanna-backend:$SHORT_SHA'
options:
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET
serviceAccount: "1037462767360-compute@developer.gserviceaccount.com"