# version: '3'
services:
  utpanna-backend:
    build: .
    image: gcr.io/utpanna-dev/utpanna-backend:latest
    ports:
      - "8080:8080"
    volumes:
      - ./data:/app/data
    environment:
      - FIREBASE_ADMINSDK_PATH=config/utpanna-dev-firebase-adminsdk-lu0ns-c9ad16a4ea.json
      - JWT_SECRET_KEY=c4c34011ed760a4cd2040b1b63adfac6fa63f21ad528040a3d8a74ce45fd4743
      - SQLALCHEMY_DATABASE_URI=sqlite:///database.db
      - JWT_ACCESS_TOKEN_EXPIRES=timedelta(days=30)