services:
  utpanna-backend:
    build: .
    image: gcr.io/utpanna-dev/utpanna-backend:latest
    ports:
      - "8080:8080"
    volumes:
      - ./data:/app/data
    depends_on:
      - db

  db:
    image: utpanna-dev-db
    restart: always
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: