version: '3'
services:
  utpanna-backend:
    build: .
    image: gcr.io/utpanna-dev/utpanna-backend:latest
    ports:
      - "8080:8080"
    volumes:
      - ./data:/app/data
    environment:
      - MYSQL_DATABASE_URI=mysql://${MYSQL_USER}:${MYSQL_PASSWORD}@db/${MYSQL_DATABASE}
      - JWT_ACCESS_TOKEN_EXPIRES=timedelta(days=30)
    depends_on:
      - db

  db:
    image: mysql:8.0
    restart: always
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: