services:
  utpanna-dev-backend:
    build: .
    image: gcr.io/utpanna-backend/utpanna-dev-backend:latest
    ports:
      - "${PORT:-8080}:${PORT:-8080}"
    environment:
      - PORT=${PORT:-8080}
      - ENV=dev