"""Add mrp and deal_price to deal table

Revision ID: 961d1295b196
Revises: 8943a76150f1
Create Date: 2024-11-10 08:08:00.144860

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '961d1295b196'
down_revision: Union[str, None] = '8943a76150f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deal', sa.Column('mrp', sa.Float(), nullable=True))
    op.add_column('deal', sa.Column('deal_price', sa.Float(), nullable=True))
    op.drop_column('deal', 'price')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deal', sa.Column('price', mysql.FLOAT(), nullable=False))
    op.drop_column('deal', 'deal_price')
    op.drop_column('deal', 'mrp')
    # ### end Alembic commands ###
