"""Added admin table and firebase auth users

Revision ID: f68a8494aeaa
Revises: e4db88e50c17
Create Date: 2024-11-04 23:31:41.493848

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'f68a8494aeaa'
down_revision: Union[str, None] = 'e4db88e50c17'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('email', table_name='user')
    op.drop_index('username', table_name='user')
    op.drop_column('user', 'password_hash')
    op.drop_column('user', 'username')
    op.drop_column('user', 'email')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('email', mysql.VARCHAR(length=120), nullable=True))
    op.add_column('user', sa.Column('username', mysql.VARCHAR(length=80), nullable=True))
    op.add_column('user', sa.Column('password_hash', mysql.VARCHAR(length=255), nullable=True))
    op.create_index('username', 'user', ['username'], unique=True)
    op.create_index('email', 'user', ['email'], unique=True)
    # ### end Alembic commands ###
